#pragma once

extern void ShowErrorMessage(std::string_view file, int line, std::string_view message);
#define SHOW_ERROR(strMsg)		ShowErrorMessage(__FILE__, __LINE__, strMsg);

// std::string -> std::wstring
inline std::wstring StringToWString(const std::string& str, UINT codePage = CP_UTF8)
{
    if (str.empty()) return L"";

    int size_needed = MultiByteToWideChar(codePage, 0, str.c_str(), -1, nullptr, 0);
    std::wstring wstr(size_needed, 0);
    MultiByteToWideChar(codePage, 0, str.c_str(), -1, &wstr[0], size_needed);

    // 마지막에 들어간 null 문자 제거
    if (!wstr.empty() && wstr.back() == L'\0')
        wstr.pop_back();

    return wstr;
}

// std::wstring -> std::string
inline std::string WStringToString(const std::wstring& wstr, UINT codePage = CP_UTF8)
{
    if (wstr.empty()) return "";

    int size_needed = WideCharToMultiByte(codePage, 0, wstr.c_str(), -1, nullptr, 0, nullptr, nullptr);
    std::string str(size_needed, 0);
    WideCharToMultiByte(codePage, 0, wstr.c_str(), -1, &str[0], size_needed, nullptr, nullptr);

    if (!str.empty() && str.back() == '\0')
        str.pop_back();

    return str;
}

inline constexpr float SmoothStep(float fX, float fMin, float fMax)
{
	if (fMin == fMax) return 0.f;
	float t = (fX - fMin) / (fMax - fMin);
	t = std::clamp(t, 0.f, 1.f);
	return t * t * (3.0f - 2.0f * t);
}

inline constexpr float SmoothStep(double dX, double dMin, double dMax)
{
	if (dMin == dMax) return 0.f;
	double t = (dX - dMin) / (dMax - dMin);
	t = std::clamp(t, 0.0, 1.0);
	return t * t * (3.0 - 2.0 * t);
}

inline constexpr float SmoothStep01(float fX)
{
	fX = std::clamp(fX, 0.0f, 1.0f);
	return fX* fX * (3.0f - 2.0f * fX);
}

inline constexpr float SmoothStep01(double dX)
{
	dX = std::clamp(dX, 0.0, 1.0);
	return dX * dX * (3.0 - 2.0 * dX);
}

inline constexpr float lerp(float t, float a, float b)
{
	return a + (b - a) * t;
}

inline constexpr double lerp(double t, double a, double b)
{
	return a + (b - a) * t;
}

template<typename T>
struct ConstantBufferSize {
	constexpr static size_t value = (sizeof(T) + 255) & (~255);
    constexpr static size_t nDescriptors = ((sizeof(T) + 255) & (~255)) / 255;
};

inline std::pair<Vector3, Vector3> GetMinMaxFromAABB(const BoundingBox& xmAABB) 
{
	return {
		Vector3{xmAABB.Center - xmAABB.Extents},
		Vector3{xmAABB.Center + xmAABB.Extents}
	};
}

inline std::pair<Vector3, Vector3> GetMinMaxFromOBB(const BoundingOrientedBox& xmOBB)
{
	XMFLOAT3 pxmf3Corners[BoundingOrientedBox::CORNER_COUNT];
	xmOBB.GetCorners(pxmf3Corners);
	BoundingBox xmAABB;
	BoundingBox::CreateFromPoints(xmAABB, BoundingOrientedBox::CORNER_COUNT, pxmf3Corners, sizeof(XMFLOAT3));
	return GetMinMaxFromAABB(xmAABB);
}

inline void CreateAABBFromOBB(OUT BoundingBox& outxmAABB, IN const BoundingOrientedBox& xmOBB) 
{
	XMFLOAT3 pxmf3Corners[BoundingOrientedBox::CORNER_COUNT];
	xmOBB.GetCorners(pxmf3Corners);

	BoundingBox::CreateFromPoints(outxmAABB, BoundingOrientedBox::CORNER_COUNT, pxmf3Corners, sizeof(XMFLOAT3));
}

/////////////////////////////////////////////////////////////////////////////////
// Unit Conversion + Literals

constexpr float CM(float v) noexcept { return v; }
constexpr float M(float v) noexcept { return v * 100.0f; }
constexpr float KM(float v) noexcept { return v * 100000.0f; }

constexpr float CM(int v) noexcept { return v; }
constexpr float M(int v) noexcept { return v * 100; }
constexpr float KM(int v) noexcept { return v * 100000; }

constexpr float operator""_cm(long double v) 
{
	return static_cast<float>(v);
}

constexpr float operator""_m(long double v) 
{
	return static_cast<float>(v * 100.0L);
}

constexpr float operator""_km(long double v) 
{
	return static_cast<float>(v * 100000.0L);
}

constexpr float operator""_cm(unsigned long long v) 
{
	return static_cast<float>(v);
}

constexpr float operator""_m(unsigned long long v)
{
	return static_cast<float>(v * 100ULL);
}

constexpr float operator""_km(unsigned long long v)
{
	return static_cast<float>(v * 100000ULL);
}



// enum to text

inline std::string SRVViewDimensionsToString(D3D12_SRV_DIMENSION d)
{
	switch (d)
	{
	case D3D12_SRV_DIMENSION_UNKNOWN: return "D3D12_SRV_DIMENSION_UNKNOWN";
	case D3D12_SRV_DIMENSION_BUFFER: return "D3D12_SRV_DIMENSION_BUFFER";
	case D3D12_SRV_DIMENSION_TEXTURE1D: return "D3D12_SRV_DIMENSION_TEXTURE1D";
	case D3D12_SRV_DIMENSION_TEXTURE1DARRAY: return "D3D12_SRV_DIMENSION_TEXTURE1DARRAY";
	case D3D12_SRV_DIMENSION_TEXTURE2D: return "D3D12_SRV_DIMENSION_TEXTURE2D";
	case D3D12_SRV_DIMENSION_TEXTURE2DARRAY: return "D3D12_SRV_DIMENSION_TEXTURE2DARRAY";
	case D3D12_SRV_DIMENSION_TEXTURE2DMS: return "D3D12_SRV_DIMENSION_TEXTURE2DMS";
	case D3D12_SRV_DIMENSION_TEXTURE2DMSARRAY: return "D3D12_SRV_DIMENSION_TEXTURE2DMSARRAY";
	case D3D12_SRV_DIMENSION_TEXTURE3D: return "D3D12_SRV_DIMENSION_TEXTURE3D";
	case D3D12_SRV_DIMENSION_TEXTURECUBE: return "D3D12_SRV_DIMENSION_TEXTURECUBE";
	case D3D12_SRV_DIMENSION_TEXTURECUBEARRAY: return "D3D12_SRV_DIMENSION_TEXTURECUBEARRAY";
	case D3D12_SRV_DIMENSION_RAYTRACING_ACCELERATION_STRUCTURE: return "D3D12_SRV_DIMENSION_RAYTRACING_ACCELERATION_STRUCTURE";
	}

	return {};
}

inline std::string RTVViewDimensionsToString(D3D12_RTV_DIMENSION d) 
{
	switch (d)
	{
	case D3D12_RTV_DIMENSION_UNKNOWN: return "D3D12_RTV_DIMENSION_UNKNOWN";
	case D3D12_RTV_DIMENSION_BUFFER: return "D3D12_RTV_DIMENSION_BUFFER";
	case D3D12_RTV_DIMENSION_TEXTURE1D: return "D3D12_RTV_DIMENSION_TEXTURE1D";
	case D3D12_RTV_DIMENSION_TEXTURE1DARRAY: return "D3D12_RTV_DIMENSION_TEXTURE1DARRAY";
	case D3D12_RTV_DIMENSION_TEXTURE2D: return "D3D12_RTV_DIMENSION_TEXTURE2D";
	case D3D12_RTV_DIMENSION_TEXTURE2DARRAY: return "D3D12_RTV_DIMENSION_TEXTURE2DARRAY";
	case D3D12_RTV_DIMENSION_TEXTURE2DMS: return "D3D12_RTV_DIMENSION_TEXTURE2DMS";
	case D3D12_RTV_DIMENSION_TEXTURE2DMSARRAY: return "D3D12_RTV_DIMENSION_TEXTURE2DMSARRAY";
	case D3D12_RTV_DIMENSION_TEXTURE3D: return "D3D12_RTV_DIMENSION_TEXTURE3D";
	}
}

inline std::string DSVViewDimensionsToString(D3D12_DSV_DIMENSION d)
{
	switch (d)
	{
	case D3D12_DSV_DIMENSION_UNKNOWN: return "D3D12_DSV_DIMENSION_UNKNOWN";
	case D3D12_DSV_DIMENSION_TEXTURE1D: return "D3D12_DSV_DIMENSION_TEXTURE1D";
	case D3D12_DSV_DIMENSION_TEXTURE1DARRAY: return "D3D12_DSV_DIMENSION_TEXTURE1DARRAY";
	case D3D12_DSV_DIMENSION_TEXTURE2D: return "D3D12_DSV_DIMENSION_TEXTURE2D";
	case D3D12_DSV_DIMENSION_TEXTURE2DARRAY: return "D3D12_DSV_DIMENSION_TEXTURE2DARRAY";
	case D3D12_DSV_DIMENSION_TEXTURE2DMS: return "D3D12_DSV_DIMENSION_TEXTURE2DMS";
	case D3D12_DSV_DIMENSION_TEXTURE2DMSARRAY: return "D3D12_DSV_DIMENSION_TEXTURE2DMSARRAY";
	}

	return {};
}

inline std::string UAVViewDimensionsToString(D3D12_UAV_DIMENSION d)
{
	switch (d)
	{
	case D3D12_UAV_DIMENSION_UNKNOWN: return "D3D12_UAV_DIMENSION_UNKNOWN";
	case D3D12_UAV_DIMENSION_BUFFER: return "D3D12_UAV_DIMENSION_BUFFER";
	case D3D12_UAV_DIMENSION_TEXTURE1D: return "D3D12_UAV_DIMENSION_TEXTURE1D";
	case D3D12_UAV_DIMENSION_TEXTURE1DARRAY: return "D3D12_UAV_DIMENSION_TEXTURE1DARRAY";
	case D3D12_UAV_DIMENSION_TEXTURE2D: return "D3D12_UAV_DIMENSION_TEXTURE2D";
	case D3D12_UAV_DIMENSION_TEXTURE2DARRAY: return "D3D12_UAV_DIMENSION_TEXTURE2DARRAY";
	case D3D12_UAV_DIMENSION_TEXTURE2DMS: return "D3D12_UAV_DIMENSION_TEXTURE2DMS";
	case D3D12_UAV_DIMENSION_TEXTURE2DMSARRAY: return "D3D12_UAV_DIMENSION_TEXTURE2DMSARRAY";
	case D3D12_UAV_DIMENSION_TEXTURE3D: return "D3D12_UAV_DIMENSION_TEXTURE3D";
	}

	return {};
}

inline std::string ResourceStateToString(D3D12_RESOURCE_STATES s) 
{
	switch (s)
	{
	case D3D12_RESOURCE_STATE_COMMON: return "D3D12_RESOURCE_STATE_COMMON or D3D12_RESOURCE_STATE_PRESENT";
	case D3D12_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER: return "D3D12_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER";
	case D3D12_RESOURCE_STATE_INDEX_BUFFER: return "D3D12_RESOURCE_STATE_INDEX_BUFFER";
	case D3D12_RESOURCE_STATE_RENDER_TARGET: return "D3D12_RESOURCE_STATE_RENDER_TARGET";
	case D3D12_RESOURCE_STATE_UNORDERED_ACCESS: return "D3D12_RESOURCE_STATE_UNORDERED_ACCESS";
	case D3D12_RESOURCE_STATE_DEPTH_WRITE: return "D3D12_RESOURCE_STATE_DEPTH_WRITE";
	case D3D12_RESOURCE_STATE_DEPTH_READ: return "D3D12_RESOURCE_STATE_DEPTH_READ";
	case D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE: return "D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE";
	case D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE: return "D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE";
	case D3D12_RESOURCE_STATE_STREAM_OUT: return "D3D12_RESOURCE_STATE_STREAM_OUT";
	case D3D12_RESOURCE_STATE_INDIRECT_ARGUMENT: return "D3D12_RESOURCE_STATE_INDIRECT_ARGUMENT or D3D12_RESOURCE_STATE_PREDICATION";
	case D3D12_RESOURCE_STATE_COPY_DEST: return "D3D12_RESOURCE_STATE_COPY_DEST";
	case D3D12_RESOURCE_STATE_COPY_SOURCE: return "D3D12_RESOURCE_STATE_COPY_SOURCE";
	case D3D12_RESOURCE_STATE_RESOLVE_DEST: return "D3D12_RESOURCE_STATE_RESOLVE_DEST";
	case D3D12_RESOURCE_STATE_RESOLVE_SOURCE: return "D3D12_RESOURCE_STATE_RESOLVE_SOURCE";
	case D3D12_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE: return "D3D12_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE";
	case D3D12_RESOURCE_STATE_SHADING_RATE_SOURCE: return "D3D12_RESOURCE_STATE_SHADING_RATE_SOURCE";
	case D3D12_RESOURCE_STATE_RESERVED_INTERNAL_8000: return "D3D12_RESOURCE_STATE_RESERVED_INTERNAL_8000";
	case D3D12_RESOURCE_STATE_RESERVED_INTERNAL_4000: return "D3D12_RESOURCE_STATE_RESERVED_INTERNAL_4000";
	case D3D12_RESOURCE_STATE_RESERVED_INTERNAL_100000: return "D3D12_RESOURCE_STATE_RESERVED_INTERNAL_100000";
	case D3D12_RESOURCE_STATE_RESERVED_INTERNAL_40000000: return "D3D12_RESOURCE_STATE_RESERVED_INTERNAL_40000000";
	case D3D12_RESOURCE_STATE_RESERVED_INTERNAL_80000000: return "D3D12_RESOURCE_STATE_RESERVED_INTERNAL_80000000";
	case D3D12_RESOURCE_STATE_GENERIC_READ: return "D3D12_RESOURCE_STATE_GENERIC_READ";
	case D3D12_RESOURCE_STATE_ALL_SHADER_RESOURCE: return "D3D12_RESOURCE_STATE_ALL_SHADER_RESOURCE";
	case D3D12_RESOURCE_STATE_VIDEO_DECODE_READ: return "D3D12_RESOURCE_STATE_VIDEO_DECODE_READ";
	case D3D12_RESOURCE_STATE_VIDEO_DECODE_WRITE: return "D3D12_RESOURCE_STATE_VIDEO_DECODE_WRITE";
	case D3D12_RESOURCE_STATE_VIDEO_PROCESS_READ: return "D3D12_RESOURCE_STATE_VIDEO_PROCESS_READ";
	case D3D12_RESOURCE_STATE_VIDEO_PROCESS_WRITE: return "D3D12_RESOURCE_STATE_VIDEO_PROCESS_WRITE";
	case D3D12_RESOURCE_STATE_VIDEO_ENCODE_READ: return "D3D12_RESOURCE_STATE_VIDEO_ENCODE_READ";
	case D3D12_RESOURCE_STATE_VIDEO_ENCODE_WRITE: return "D3D12_RESOURCE_STATE_VIDEO_ENCODE_WRITE";
	}

	return {};
}

inline std::string DXGIFormatToString(DXGI_FORMAT format)
{
	switch (format)
	{
	case DXGI_FORMAT_UNKNOWN:					return "DXGI_FORMAT_UNKNOWN";
	case DXGI_FORMAT_R32G32B32A32_TYPELESS:		return "DXGI_FORMAT_UNKNOWN";
	case DXGI_FORMAT_R32G32B32A32_FLOAT: return "DXGI_FORMAT_R32G32B32A32_FLOAT";
	case DXGI_FORMAT_R32G32B32A32_UINT: return "DXGI_FORMAT_R32G32B32A32_UINT";
	case DXGI_FORMAT_R32G32B32A32_SINT: return "DXGI_FORMAT_R32G32B32A32_SINT";
	case DXGI_FORMAT_R32G32B32_TYPELESS: return "DXGI_FORMAT_R32G32B32_TYPELESS";
	case DXGI_FORMAT_R32G32B32_FLOAT: return "DXGI_FORMAT_R32G32B32_FLOAT";
	case DXGI_FORMAT_R32G32B32_UINT: return "DXGI_FORMAT_R32G32B32_UINT";
	case DXGI_FORMAT_R32G32B32_SINT: return "DXGI_FORMAT_R32G32B32_SINT";
	case DXGI_FORMAT_R16G16B16A16_TYPELESS: return "DXGI_FORMAT_R16G16B16A16_TYPELESS";
	case DXGI_FORMAT_R16G16B16A16_FLOAT: return "DXGI_FORMAT_R16G16B16A16_FLOAT";
	case DXGI_FORMAT_R16G16B16A16_UNORM: return "DXGI_FORMAT_R16G16B16A16_UNORM";
	case DXGI_FORMAT_R16G16B16A16_UINT: return "DXGI_FORMAT_R16G16B16A16_UINT";
	case DXGI_FORMAT_R16G16B16A16_SNORM: return "DXGI_FORMAT_R16G16B16A16_SNORM";
	case DXGI_FORMAT_R16G16B16A16_SINT: return "DXGI_FORMAT_R16G16B16A16_SINT";
	case DXGI_FORMAT_R32G32_TYPELESS: return "DXGI_FORMAT_R32G32_TYPELESS";
	case DXGI_FORMAT_R32G32_FLOAT: return "DXGI_FORMAT_R32G32_FLOAT";
	case DXGI_FORMAT_R32G32_UINT: return "DXGI_FORMAT_R32G32_UINT";
	case DXGI_FORMAT_R32G32_SINT: return "DXGI_FORMAT_R32G32_SINT";
	case DXGI_FORMAT_R32G8X24_TYPELESS: return "DXGI_FORMAT_R32G8X24_TYPELESS";
	case DXGI_FORMAT_D32_FLOAT_S8X24_UINT: return "DXGI_FORMAT_D32_FLOAT_S8X24_UINT";
	case DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS: return "DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS";
	case DXGI_FORMAT_X32_TYPELESS_G8X24_UINT: return "DXGI_FORMAT_X32_TYPELESS_G8X24_UINT";
	case DXGI_FORMAT_R10G10B10A2_TYPELESS: return "DXGI_FORMAT_R10G10B10A2_TYPELESS";
	case DXGI_FORMAT_R10G10B10A2_UNORM: return "DXGI_FORMAT_R10G10B10A2_UNORM";
	case DXGI_FORMAT_R10G10B10A2_UINT: return "DXGI_FORMAT_R10G10B10A2_UINT";
	case DXGI_FORMAT_R11G11B10_FLOAT: return "DXGI_FORMAT_R11G11B10_FLOAT";
	case DXGI_FORMAT_R8G8B8A8_TYPELESS: return "DXGI_FORMAT_R8G8B8A8_TYPELESS";
	case DXGI_FORMAT_R8G8B8A8_UNORM: return "DXGI_FORMAT_R8G8B8A8_UNORM";
	case DXGI_FORMAT_R8G8B8A8_UNORM_SRGB: return "DXGI_FORMAT_R8G8B8A8_UNORM_SRGB";
	case DXGI_FORMAT_R8G8B8A8_UINT: return "DXGI_FORMAT_R8G8B8A8_UINT";
	case DXGI_FORMAT_R8G8B8A8_SNORM: return "DXGI_FORMAT_R8G8B8A8_SNORM";
	case DXGI_FORMAT_R8G8B8A8_SINT: return "DXGI_FORMAT_R8G8B8A8_SINT";
	case DXGI_FORMAT_R16G16_TYPELESS: return "DXGI_FORMAT_R16G16_TYPELESS";
	case DXGI_FORMAT_R16G16_FLOAT: return "DXGI_FORMAT_R16G16_FLOAT";
	case DXGI_FORMAT_R16G16_UNORM: return "DXGI_FORMAT_R16G16_UNORM";
	case DXGI_FORMAT_R16G16_UINT: return "DXGI_FORMAT_R16G16_UINT";
	case DXGI_FORMAT_R16G16_SNORM: return "DXGI_FORMAT_R16G16_SNORM";
	case DXGI_FORMAT_R16G16_SINT: return "DXGI_FORMAT_R16G16_SINT";
	case DXGI_FORMAT_R32_TYPELESS: return "DXGI_FORMAT_R32_TYPELESS";
	case DXGI_FORMAT_D32_FLOAT: return "DXGI_FORMAT_D32_FLOAT";
	case DXGI_FORMAT_R32_FLOAT: return "DXGI_FORMAT_R32_FLOAT";
	case DXGI_FORMAT_R32_UINT: return "DXGI_FORMAT_R32_UINT";
	case DXGI_FORMAT_R32_SINT: return "DXGI_FORMAT_R32_SINT";
	case DXGI_FORMAT_R24G8_TYPELESS: return "DXGI_FORMAT_R24G8_TYPELESS";
	case DXGI_FORMAT_D24_UNORM_S8_UINT: return "DXGI_FORMAT_D24_UNORM_S8_UINT";
	case DXGI_FORMAT_R24_UNORM_X8_TYPELESS: return "DXGI_FORMAT_R24_UNORM_X8_TYPELESS";
	case DXGI_FORMAT_X24_TYPELESS_G8_UINT: return "DXGI_FORMAT_X24_TYPELESS_G8_UINT";
	case DXGI_FORMAT_R8G8_TYPELESS: return "DXGI_FORMAT_R8G8_TYPELESS";
	case DXGI_FORMAT_R8G8_UNORM: return "DXGI_FORMAT_R8G8_UNORM";
	case DXGI_FORMAT_R8G8_UINT: return "DXGI_FORMAT_R8G8_UINT";
	case DXGI_FORMAT_R8G8_SNORM: return "DXGI_FORMAT_R8G8_SNORM";
	case DXGI_FORMAT_R8G8_SINT: return "DXGI_FORMAT_R8G8_SINT";
	case DXGI_FORMAT_R16_TYPELESS: return "DXGI_FORMAT_R16_TYPELESS";
	case DXGI_FORMAT_R16_FLOAT: return "DXGI_FORMAT_R16_FLOAT";
	case DXGI_FORMAT_D16_UNORM: return "DXGI_FORMAT_D16_UNORM";
	case DXGI_FORMAT_R16_UNORM: return "DXGI_FORMAT_R16_UNORM";
	case DXGI_FORMAT_R16_UINT: return "DXGI_FORMAT_R16_UINT";
	case DXGI_FORMAT_R16_SNORM: return "DXGI_FORMAT_R16_SNORM";
	case DXGI_FORMAT_R16_SINT: return "DXGI_FORMAT_R16_SINT";
	case DXGI_FORMAT_R8_TYPELESS: return "DXGI_FORMAT_R8_TYPELESS";
	case DXGI_FORMAT_R8_UNORM: return "DXGI_FORMAT_R8_UNORM";
	case DXGI_FORMAT_R8_UINT: return "DXGI_FORMAT_R8_UINT";
	case DXGI_FORMAT_R8_SNORM: return "DXGI_FORMAT_R8_SNORM";
	case DXGI_FORMAT_R8_SINT: return "DXGI_FORMAT_R8_SINT";
	case DXGI_FORMAT_A8_UNORM: return "DXGI_FORMAT_A8_UNORM";
	case DXGI_FORMAT_R1_UNORM: return "DXGI_FORMAT_R1_UNORM";
	case DXGI_FORMAT_R9G9B9E5_SHAREDEXP: return "DXGI_FORMAT_R9G9B9E5_SHAREDEXP";
	case DXGI_FORMAT_R8G8_B8G8_UNORM: return "DXGI_FORMAT_R8G8_B8G8_UNORM";
	case DXGI_FORMAT_G8R8_G8B8_UNORM: return "DXGI_FORMAT_G8R8_G8B8_UNORM";
	case DXGI_FORMAT_BC1_TYPELESS: return "DXGI_FORMAT_BC1_TYPELESS";
	case DXGI_FORMAT_BC1_UNORM: return "DXGI_FORMAT_BC1_UNORM";
	case DXGI_FORMAT_BC1_UNORM_SRGB: return "DXGI_FORMAT_BC1_UNORM_SRGB";
	case DXGI_FORMAT_BC2_TYPELESS: return "DXGI_FORMAT_BC2_TYPELESS";
	case DXGI_FORMAT_BC2_UNORM: return "DXGI_FORMAT_BC2_UNORM";
	case DXGI_FORMAT_BC2_UNORM_SRGB: return "DXGI_FORMAT_BC2_UNORM_SRGB";
	case DXGI_FORMAT_BC3_TYPELESS: return "DXGI_FORMAT_BC3_TYPELESS";
	case DXGI_FORMAT_BC3_UNORM: return "DXGI_FORMAT_BC3_UNORM";
	case DXGI_FORMAT_BC3_UNORM_SRGB: return "DXGI_FORMAT_BC3_UNORM_SRGB";
	case DXGI_FORMAT_BC4_TYPELESS: return "DXGI_FORMAT_BC4_TYPELESS";
	case DXGI_FORMAT_BC4_UNORM: return "DXGI_FORMAT_BC4_UNORM";
	case DXGI_FORMAT_BC4_SNORM: return "DXGI_FORMAT_BC4_SNORM";
	case DXGI_FORMAT_BC5_TYPELESS: return "DXGI_FORMAT_BC5_TYPELESS";
	case DXGI_FORMAT_BC5_UNORM: return "DXGI_FORMAT_BC5_UNORM";
	case DXGI_FORMAT_BC5_SNORM: return "DXGI_FORMAT_BC5_SNORM";
	case DXGI_FORMAT_B5G6R5_UNORM: return "DXGI_FORMAT_B5G6R5_UNORM";
	case DXGI_FORMAT_B5G5R5A1_UNORM: return "DXGI_FORMAT_B5G5R5A1_UNORM";
	case DXGI_FORMAT_B8G8R8A8_UNORM: return "DXGI_FORMAT_B8G8R8A8_UNORM";
	case DXGI_FORMAT_B8G8R8X8_UNORM: return "DXGI_FORMAT_B8G8R8X8_UNORM";
	case DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM: return "DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM";
	case DXGI_FORMAT_B8G8R8A8_TYPELESS: return "DXGI_FORMAT_B8G8R8A8_TYPELESS";
	case DXGI_FORMAT_B8G8R8A8_UNORM_SRGB: return "DXGI_FORMAT_B8G8R8A8_UNORM_SRGB";
	case DXGI_FORMAT_B8G8R8X8_TYPELESS: return "DXGI_FORMAT_B8G8R8X8_TYPELESS";
	case DXGI_FORMAT_B8G8R8X8_UNORM_SRGB: return "DXGI_FORMAT_B8G8R8X8_UNORM_SRGB";
	case DXGI_FORMAT_BC6H_TYPELESS: return "DXGI_FORMAT_BC6H_TYPELESS";
	case DXGI_FORMAT_BC6H_UF16: return "DXGI_FORMAT_BC6H_UF16";
	case DXGI_FORMAT_BC6H_SF16: return "DXGI_FORMAT_BC6H_SF16";
	case DXGI_FORMAT_BC7_TYPELESS: return "DXGI_FORMAT_BC7_TYPELESS";
	case DXGI_FORMAT_BC7_UNORM: return "DXGI_FORMAT_BC7_UNORM";
	case DXGI_FORMAT_BC7_UNORM_SRGB: return "DXGI_FORMAT_BC7_UNORM_SRGB";
	case DXGI_FORMAT_AYUV: return "DXGI_FORMAT_AYUV";
	case DXGI_FORMAT_Y410: return "DXGI_FORMAT_Y410";
	case DXGI_FORMAT_Y416: return "DXGI_FORMAT_Y416";
	case DXGI_FORMAT_NV12: return "DXGI_FORMAT_NV12";
	case DXGI_FORMAT_P010: return "DXGI_FORMAT_P010";
	case DXGI_FORMAT_P016: return "DXGI_FORMAT_P016";
	case DXGI_FORMAT_420_OPAQUE: return "DXGI_FORMAT_420_OPAQUE";
	case DXGI_FORMAT_YUY2: return "DXGI_FORMAT_YUY2";
	case DXGI_FORMAT_Y210: return "DXGI_FORMAT_Y210";
	case DXGI_FORMAT_Y216: return "DXGI_FORMAT_Y216";
	case DXGI_FORMAT_NV11: return "DXGI_FORMAT_NV11";
	case DXGI_FORMAT_AI44: return "DXGI_FORMAT_AI44";
	case DXGI_FORMAT_IA44: return "DXGI_FORMAT_IA44";
	case DXGI_FORMAT_P8: return "DXGI_FORMAT_P8";
	case DXGI_FORMAT_A8P8: return "DXGI_FORMAT_A8P8";
	case DXGI_FORMAT_B4G4R4A4_UNORM: return "DXGI_FORMAT_B4G4R4A4_UNORM";
	case DXGI_FORMAT_P208: return "DXGI_FORMAT_P208";
	case DXGI_FORMAT_V208: return "DXGI_FORMAT_V208";
	case DXGI_FORMAT_V408: return "DXGI_FORMAT_V408";
	case DXGI_FORMAT_SAMPLER_FEEDBACK_MIN_MIP_OPAQUE: return "DXGI_FORMAT_SAMPLER_FEEDBACK_MIN_MIP_OPAQUE";
	case DXGI_FORMAT_SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE: return "DXGI_FORMAT_SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE";
	case DXGI_FORMAT_A4B4G4R4_UNORM: return "DXGI_FORMAT_A4B4G4R4_UNORM";
	case DXGI_FORMAT_FORCE_UINT: return "DXGI_FORMAT_FORCE_UINT";
	}

	return {};
}
